--Add products
INSERT INTO product (name, description, price, stock_quantity, category) VALUES
('Industrial Drill', 'High-power industrial drill for heavy-duty use', 299.99, 50, 'Tools'),
('Office Chair', 'Ergonomic office chair with lumbar support', 89.99, 200, 'Office Furniture'),
('Laptop', '15-inch laptop with 8GB RAM and 256GB SSD', 799.99, 100, 'Electronics'),
('Smartphone', 'Latest model smartphone with 128GB storage', 999.99, 150, 'Electronics'),
('LED Monitor', '24-inch LED monitor with Full HD resolution', 149.99, 120, 'Electronics'),
('Desk Lamp', 'Adjustable desk lamp with USB charging port', 39.99, 300, 'Office Supplies'),
('Wireless Mouse', 'Ergonomic wireless mouse with USB receiver', 29.99, 400, 'Electronics'),
('Coffee Maker', 'Automatic coffee maker with programmable settings', 69.99, 100, 'Appliances'),
('3D Printer', 'High-precision 3D printer for professional use', 499.99, 30, 'Electronics'),
('Projector', 'Portable projector with HD resolution', 199.99, 80, 'Electronics'),
('Tablet', '10-inch tablet with 64GB storage and WiFi', 399.99, 150, 'Electronics'),
('External Hard Drive', '1TB external hard drive with USB 3.0', 59.99, 200, 'Electronics'),
('Printer', 'All-in-one printer with scanning and copying functions', 129.99, 100, 'Office Supplies'),
('Router', 'High-speed wireless router with dual-band support', 79.99, 120, 'Electronics'),
('Keyboard', 'Mechanical keyboard with backlit keys', 59.99, 150, 'Electronics'),
('Smartwatch', 'Fitness smartwatch with heart rate monitor', 199.99, 100, 'Electronics'),
('Bluetooth Speaker', 'Portable Bluetooth speaker with deep bass', 49.99, 200, 'Electronics'),
('Air Conditioner', 'Portable air conditioner with remote control', 299.99, 50, 'Appliances'),
('Electric Scooter', 'Foldable electric scooter with 15-mile range', 399.99, 75, 'Electronics'),
('Surveillance Camera', 'HD surveillance camera with night vision', 99.99, 100, 'Electronics'),
('Office Desk', 'Spacious office desk with drawers', 199.99, 50, 'Office Furniture'),
('Conference Table', 'Large conference table for meeting rooms', 599.99, 20, 'Office Furniture'),
('Water Dispenser', 'Hot and cold water dispenser', 129.99, 100, 'Appliances'),
('Shredder', 'High-security shredder for office use', 79.99, 150, 'Office Supplies'),
('Whiteboard', 'Magnetic whiteboard with stand', 49.99, 200, 'Office Supplies'),
('Laser Pointer', 'Professional laser pointer for presentations', 19.99, 300, 'Office Supplies'),
('File Cabinet', '4-drawer vertical file cabinet', 99.99, 80, 'Office Furniture'),
('Notebook', 'Leather-bound notebook for business meetings', 14.99, 500, 'Office Supplies'),
('Pen Set', 'Luxury pen set with case', 29.99, 400, 'Office Supplies'),
('Laptop Stand', 'Adjustable laptop stand for desk use', 39.99, 200, 'Office Supplies'),
('Wireless Charger', 'Fast wireless charger for smartphones', 24.99, 250, 'Electronics'),
('USB Hub', '7-port USB hub with power adapter', 19.99, 300, 'Electronics'),
('Headphones', 'Noise-cancelling over-ear headphones', 149.99, 100, 'Electronics'),
('Webcam', 'HD webcam with built-in microphone', 49.99, 150, 'Electronics'),
('Docking Station', 'Universal docking station for laptops', 99.99, 120, 'Electronics'),
('Smart Thermostat', 'Programmable smart thermostat with WiFi', 199.99, 80, 'Appliances'),
('Smart Light Bulb', 'Color-changing smart light bulb with remote control', 14.99, 400, 'Electronics'),
('Portable Charger', 'High-capacity portable charger with USB-C', 39.99, 200, 'Electronics'),
('Electric Kettle', 'Stainless steel electric kettle with auto shut-off', 49.99, 150, 'Appliances'),
('Vacuum Cleaner', 'High-power cordless vacuum cleaner', 199.99, 50, 'Appliances'),
('Microwave Oven', 'Compact microwave oven with multiple settings', 99.99, 100, 'Appliances'),
('Toaster', '4-slice toaster with adjustable settings', 29.99, 200, 'Appliances'),
('Blender', 'High-speed blender for smoothies and shakes', 59.99, 150, 'Appliances'),
('Standing Desk', 'Adjustable height standing desk', 299.99, 70, 'Office Furniture'),
('Paper Cutter', 'Precision paper cutter for office use', 49.99, 100, 'Office Supplies'),
('Desk Organizer', 'Multi-functional desk organizer with drawers', 24.99, 250, 'Office Supplies'),
('Label Maker', 'Portable label maker with QWERTY keyboard', 34.99, 150, 'Office Supplies'),
('Clipboards', 'Set of 10 letter-size clipboards', 19.99, 300, 'Office Supplies'),
('Paper Shredder Oil', 'Pack of 12 shredder lubricant sheets', 12.99, 400, 'Office Supplies');

